name: Pruebas Unitarias

on:
  push:
    branches:
      - main
jobs:
  Pruebas-Unitarias:
    runs-on: ubuntu-latest

    steps:
    - name: Revisar código
      uses: actions/checkout@v2

    - name: Preparar Node
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Instalar dependencias
      run: |
        npm install

    - name: Ejecutar pruebas
      run: |
        npm test